package com.fiap.comparecimento.domain.enuns;

public enum ClassificacaoPacienteEnum {
    MUITO_CONFIAVEL,
    CONFIAVEL,
    COMPARECIMENTO_PROVAVEL,
    COMPARECIMENTO_INCERTO,
    BAIXA_PROBABILIDADE_DE_COMPARECIMENTO,
    PROVAVEL_NAO_COMPARECIMENTO,
    CRITICO,
    REALOCACAO_POSSIVEL,
    REALOCACAO_IMEDIATA
}
